### ISSUE TITLE
links are not rendered correctly when link name contains []

### ISSUE THREAD

**Issue by BigMichi1** [bsorrentino/maven-confluence-plugin#226]
i have in a markdown file the following lines which are rendered 
```md
## Properties

| name | description | type | default values | since |
|------|-------------|------|----------------|-------|
| packagePatterns | regular expression | [String[]][stringArray] | `[]` | 1.2.0 |
| annotationNames | full qualified class name or simple class name of an annotation | [String[]][stringArray] | `[]` | 1.0.0 |

[stringArray]: https://checkstyle.sourceforge.io/property_types.html#String.5B.5D
```

these will be rendered as

![Screenshot_20200904_104035](https://user-images.githubusercontent.com/91786/92219612-1baebf00-ee9b-11ea-857f-a779b9c9a0c5.png)

**Comment by bsorrentino** [comment]
Hi @BigMichi1 thanks for feedback 

This looks like a bug in translation I'll work to fix this

**Comment by bsorrentino** [comment]
Hi @BigMichi1

I've fixed the problem on `commonmark' markdown parser implementation and deployed the version `6.9.1-SNAPSHOT` for  test.

Let me know if you have a chance to test it

**Comment by bsorrentino** [comment]
Hi @BigMichi1 

Seems that fix for **legacy pegdown` implementation** will be a bit harder. 

Probably I'll take in consideration idea not fix it.

So take in consideration to use (if you not do it yet) commonmark implementation

**Comment by BigMichi1** [comment]
using the fixed commonmark implementation works for the link issue, but 3 new issues appeared, I'm not sure if this is related to this ticket or it should be a new one:
- after the end of an enumeration, the next paragraph/sentence/headline will be indented, so that it looks like it is included in the enumeration
- a whitespace between two words is missing when there is a line break in an enumeration between these two words
- when there is a { or } in an inline text the server fails with error 500 and says macro unknown

see sample markdown file in this file which contains all three issues
[check.zip](https://github.com/bsorrentino/maven-confluence-plugin/files/5230249/check.zip)

there 500 error is:
` Response{protocol=h2, code=500, message=, url=https://localhost/confluence/rest/api/content/1146889}
[ERROR] {"statusCode":500,"data":{"authorized":false,"valid":true,"allowedInReadOnlyMode":true,"errors":[],"successful":false},"message":"com.atlassian.confluence.content.render.xhtml.migration.exceptions.UnknownMacroMigrationException: The macro ' \"foo\", \"bar\" ' is unknown.","reason":"Internal Server Error"}
`

when removing this line the result looks like:
![Screenshot_20200916_090717](https://user-images.githubusercontent.com/91786/93303604-0ec78f00-f7fc-11ea-9ee1-3681844a87ae.png)
you can see here the missing whitespace between type and has, so on the page it is typehas, and also the wrong indention of "Happy Coding"

**Comment by bsorrentino** [comment]
Hi @BigMichi1  thank you for the test and deep analysis, I'll check this new unexpected behavior

**Comment by bsorrentino** [comment]
Hi @BigMichi1

I've fixed the problem on **commonmark** markdown parser implementation and deployed the version `6.9.1-SNAPSHOT` for  test.

Let me know if you have a chance to test it

**Comment by BigMichi1** [comment]
the issue with the macro disappeared, very good, the only thing that is left is the wrong indention of "Happy Coding"

```
- An Aspect bean does not contain any `@Transactional` annotation

Happy Coding

## Properties
```
still shows this when published to confluence:

![Screenshot_20200918_125652](https://user-images.githubusercontent.com/91786/93590235-76254080-f9ae-11ea-8fbb-d7b5ce524e0e.png)

but according to the md file it should render like this (screenshot taken from intellij):

![Screenshot_20200918_125802](https://user-images.githubusercontent.com/91786/93590343-9e14a400-f9ae-11ea-9c5f-8e0fd8580faa.png)

**Comment by bsorrentino** [comment]
hi @BigMichi1 

I faced with your same problem. I My solution has been adding a quote symbol ( it keeps compatibility to both formats)

```markdown
- An Aspect bean does not contain any `@Transactional` annotation
>
Happy Coding

## Properties
```
