### ISSUE TITLE
NullPointerException // error generating report

### ISSUE THREAD

**Issue by TheFrogAndy** [bsorrentino/maven-confluence-plugin#253]
Hi,

i am getting following error and just can't figure out what i am missing:
```
2021-07-14T15:15:51.853  [INFO] --- confluence-reporting-maven-plugin:7.2:deploy (confluence-deploy) @ application-templateservice-ejb ---
2021-07-14T15:15:51.853  [INFO] executeReport isSnapshot = [false] isRemoveSnapshots = [false]
2021-07-14T15:15:51.853  Site
2021-07-14T15:15:51.853   Labels
2021-07-14T15:15:51.853    docc_docs
2021-07-14T15:15:51.853   index.confluence
2021-07-14T15:15:51.853  - templateservice.confluence
2021-07-14T15:15:52.371  [ERROR] error generating report
2021-07-14T15:15:52.372  java.lang.NullPointerException
2021-07-14T15:15:52.372      at org.apache.maven.project.artifact.MavenMetadataSource.retrieve (MavenMetadataSource.java:183)
2021-07-14T15:15:52.372      at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse (DefaultLegacyArtifactCollector.java:551)
2021-07-14T15:15:52.372      at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:148)
2021-07-14T15:15:52.372      at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:102)
2021-07-14T15:15:52.372      at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:804)
2021-07-14T15:15:52.372      at org.bsc.mojo.ConfluenceDeployMojo.resolveProject (ConfluenceDeployMojo.java:619)
2021-07-14T15:15:52.372      at org.bsc.mojo.ConfluenceDeployMojo.generateProjectHomeTemplate (ConfluenceDeployMojo.java:428)
2021-07-14T15:15:52.372      at org.bsc.mojo.ConfluenceDeployMojo.lambda$getHomeContent$3 (ConfluenceDeployMojo.java:541)
2021-07-14T15:15:52.373      at java.util.concurrent.CompletableFuture.uniComposeStage (CompletableFuture.java:995)
2021-07-14T15:15:52.373      at java.util.concurrent.CompletableFuture.thenCompose (CompletableFuture.java:2137)
2021-07-14T15:15:52.373      at org.bsc.mojo.ConfluenceDeployMojo.getHomeContent (ConfluenceDeployMojo.java:533)
2021-07-14T15:15:52.373      at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$5 (ConfluenceDeployMojo.java:574)
2021-07-14T15:15:52.373      at org.bsc.mojo.AbstractConfluenceDeployMojo.lambda$updatePageIfNeeded$3 (AbstractConfluenceDeployMojo.java:343)
2021-07-14T15:15:52.373      at org.bsc.mojo.AbstractConfluenceDeployMojo.lambda$canProceedToUpdatePage$28 (AbstractConfluenceDeployMojo.java:505)
2021-07-14T15:15:52.373      at java.util.Optional.orElseGet (Optional.java:267)
2021-07-14T15:15:52.373      at org.bsc.mojo.AbstractConfluenceDeployMojo.canProceedToUpdatePage (AbstractConfluenceDeployMojo.java:505)
2021-07-14T15:15:52.373      at org.bsc.mojo.AbstractConfluenceDeployMojo.updatePageIfNeeded (AbstractConfluenceDeployMojo.java:342)
2021-07-14T15:15:52.373      at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$6 (ConfluenceDeployMojo.java:573)
2021-07-14T15:15:52.374      at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$10 (ConfluenceDeployMojo.java:588)
```

I am using maven version 3.6.3
Can anyone help me?

Thanks

**Comment by bsorrentino** [comment]
Hi @TheFrogAndy 

I'm going to verify the problem. It seems related when the plugin try to collect dependencies info for generate dependencies report.

**Comment by bsorrentino** [comment]
Hi @TheFrogAndy 

Meanwhile I've deployed version `7.3-SNAPSHOT` with a simple fix that ignore NPE (probably the deps report will be not generated correctly) but overall process work

**Comment by TheFrogAndy** [comment]
Hi @bsorrentino,

still getting the error:

`[ERROR] error generating report
java.lang.NullPointerException
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieve (MavenMetadataSource.java:183)
    at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse (DefaultLegacyArtifactCollector.java:551)
    at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:148)
    at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:102)
    at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect (DefaultLegacyArtifactCollector.java:804)
    at org.bsc.mojo.ConfluenceDeployMojo.resolveProject (ConfluenceDeployMojo.java:619)
    at org.bsc.mojo.ConfluenceDeployMojo.generateProjectHomeTemplate (ConfluenceDeployMojo.java:428)
    at org.bsc.mojo.ConfluenceDeployMojo.lambda$getHomeContent$3 (ConfluenceDeployMojo.java:541)
    at java.util.concurrent.CompletableFuture.uniComposeStage (CompletableFuture.java:981)
    at java.util.concurrent.CompletableFuture.thenCompose (CompletableFuture.java:2124)
    at org.bsc.mojo.ConfluenceDeployMojo.getHomeContent (ConfluenceDeployMojo.java:533)
    at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$8 (ConfluenceDeployMojo.java:578)
    at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$10 (ConfluenceDeployMojo.java:589)
    at java.util.concurrent.CompletableFuture.uniComposeStage (CompletableFuture.java:981)
    at java.util.concurrent.CompletableFuture.thenCompose (CompletableFuture.java:2124)
    at org.bsc.mojo.ConfluenceDeployMojo.lambda$generateProjectReport$13 (ConfluenceDeployMojo.java:586)
    at java.util.concurrent.CompletableFuture.uniCompose (CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire (CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete (CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1595)
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec (CompletableFuture.java:1582)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask (ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:157)`

**Comment by TheFrogAndy** [comment]
Hm... seems to be 7.3-SNAPSHOT does not contain this fix... as soon as i download the plugin source and do a "mvn install" i get your fixed line to work.

So I think it is fixed. Can you release a new stable version?

Thanks

**Comment by bsorrentino** [comment]
fix released in version `7.2.1`
